/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
    CEXCEPTION_T e; \
    Try { \
      setUp(); \
      TestFunc(); \
    } Catch(e) { TEST_ASSERT_EQUAL_HEX32_MESSAGE(CEXCEPTION_NONE, e, "Unhandled Exception!"); } \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>
#include "CException.h"

int GlobalExpectCount;
int GlobalVerifyOrder;
char* GlobalOrderError;

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_justTryingOutTryCatch_should_throw_exception(void);
extern void test_addPositiveNumber_should_add_two_positive_values_correctly(void);
extern void test_addPositiveNumber_should_add_throw_an_exception_indication_first_value_is_negative(void);
extern void test_addPositiveNumber_should_add_throw_an_exception_indication_second_value_is_negative(void);
extern void test_addPositiveNumber_should_add_throw_an_exception_indication_both_value_is_negative(void);


//=======Test Reset Option=====
void resetTest()
{
  tearDown();
  setUp();
}


//=======MAIN=====
int main(void)
{
  Unity.TestFile = "test_TryCatch.c";
  UnityBegin();
  RUN_TEST(test_justTryingOutTryCatch_should_throw_exception, 18);
  RUN_TEST(test_addPositiveNumber_should_add_two_positive_values_correctly, 26);
  RUN_TEST(test_addPositiveNumber_should_add_throw_an_exception_indication_first_value_is_negative, 31);
  RUN_TEST(test_addPositiveNumber_should_add_throw_an_exception_indication_second_value_is_negative, 43);
  RUN_TEST(test_addPositiveNumber_should_add_throw_an_exception_indication_both_value_is_negative, 55);

  return (UnityEnd());
}
